// Generated by CoffeeScript 1.8.0
var async, createAudit, createAuditTable, createWidget, createWidgetTable, db, widget;

async = require('async');

db = require('pg-db')();


/*
Add an event handler to log all executed SQL:
 */

db.on('execute', function(data) {
  return console.log('SQL: %j', data.sql);
});

createWidgetTable = function(cb) {
  var sql;
  sql = "CREATE TABLE IF NOT EXISTS widget (\n  name      text,\n  price     numeric,\n  quantity  int\n)";
  return db.update(sql, function(err, rowCount) {
    return cb(err);
  });
};

createAuditTable = function(cb) {
  var sql;
  sql = "CREATE TABLE IF NOT EXISTS audit (\n  message     text,\n  created_at  timestamptz DEFAULT now()\n)";
  return db.update(sql, function(err, rowCount) {
    return cb(err);
  });
};

createWidget = function(widget, cb) {
  var sql;
  sql = "INSERT INTO widget\n(name, price, quantity)\nVALUES\n(:name, :price, :quantity)";
  return db.update(sql, widget, function(err, rowCount) {
    console.log('Insert count: %s rows', rowCount);
    return cb(err);
  });
};

createAudit = function(message, cb) {
  var sql;
  sql = "INSERT INTO audit\n(message)\nVALUES\n(:message)";
  return db.update(sql, {
    message: message
  }, function(err, rowCount) {
    console.log('Insert count: %s rows', rowCount);
    return cb(err);
  });
};

widget = {
  name: 'Foobar',
  price: 123.45,
  quantity: 200
};

db.tx.series([
  createWidgetTable, createAuditTable, function(cb) {
    return createWidget(widget, cb);
  }, function(cb) {
    return createAudit('Created widget with name: ' + widget.name, cb);
  }
], function(err) {
  if (err) {
    console.error('Transaction error: %s', err);
  } else {
    console.log('Transaction completed successfully');
  }
  return db.end();
});
